baseurl = "https://s3-ap-northeast-1.amazonaws.com/takusemba.com"
title = "Hi, Im TakuSemba"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[--><h3>I Love Internet. Im a Android developer.</h3><!--]-->'
  logo = "fa-code"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/takusemba"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/takusemba"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/taku_semba"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/TakuSemba"

[languages]
[languages.en]
languageName = "English"
weight = 1